### ISSUE TITLE
Add an API to support querying of leaderboard statistics

### ISSUE THREAD

**Issue by hannosch** [JaredKerim-Mozilla/leaderboard-server#38] opened 2015-07-30 15:41 UTC
Moved from mozilla/ichnaea#313:

crankycoder commented on 23 Sep 2014

This is a short term stop gap measure to help support mozilla/ichnaea#312 until we have full FxA and Galaxy leaderboard integration working.

We want to be able to provide basic metrics to Mozilla Reps during the Stumbling in a Box parties.

Metrics should be scoped to a single mozilla rep.

It's sufficient for now to be able to provide the same metrics we have on the leaderboard.

**Comment by jaredkerim** [comment] 2015-07-30 17:10
All leaderboard statistics are queryable via API by design, closing this.

**Closed by jaredkerim** 2015-07-30 17:10 UTC
